-- 코드를 입력하세요
SELECT P.PRODUCT_CODE,SUM(P.PRICE* O.SALES_AMOUNT)as SALES
from PRODUCT as P join OFFLINE_SALE as O
on O.PRODUCT_ID =P.PRODUCT_ID
group By P.PRODUCT_CODE
order by SALES DESC , PRODUCT_CODE ASC